FROM node:latest

RUN npm install -g pnpm
WORKDIR /var/www
COPY package*.json ./
COPY .npmrc ./
RUN pnpm install
COPY . .
RUN pnpm run build

FROM nginx:latest

COPY --from=0 /var/www/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
