services:
  backend:
    user: 1000:1000
    build:
      context: ./backend
      dockerfile: dockerfile
    command: bash -c "composer install && php artisan migrate:fresh --seed --force && php -S 0.0.0.0:8000 -t public"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    ports:
      - '8001:8000'
    volumes:
      - './backend:/var/www'

  frontend:
    user: 1000:1000
    build:
      context: ./frontend
      dockerfile: dockerfile-dev
    ports:
      - '8080:8080'
      - '80:80'
    restart: unless-stopped
    command: bash -c "npm install && npm run start"
    volumes:
      - './frontend:/var/www'

  db:
    user: 1000:1000
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3333:3306
    volumes:
      - './DB:/var/lib/mysql'
