FROM php:8.0-cli

RUN apt-get update -y \
    && apt-get install -y libmcrypt-dev \
    libonig-dev \
    zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mbstring pdo_mysql

WORKDIR /var/www

COPY . .
